### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by kd8azz** [bazelbuild/e4b#10]
# About Eclipse

Eclipse IDE for Java Developers
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600
# Error upon installation

An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: http://bazelbuild.github.io/e4b/p2updatesite/plugins/com.google.devtools.bazel.e4b_0.0.1.201604271311.jar.
http://bazelbuild.github.io/e4b/p2updatesite/plugins/com.google.devtools.bazel.e4b_0.0.1.201604271311.jar
Artifact not found: http://bazelbuild.github.io/e4b/p2updatesite/features/com.google.devtools.bazel.e4b.feature_0.0.1.201604271311.jar.
http://bazelbuild.github.io/e4b/p2updatesite/features/com.google.devtools.bazel.e4b.feature_0.0.1.201604271311.jar

**Comment by kd8azz** [comment]
Ubuntu GNOME 16.04.1 LTS

**Comment by damienmg** [comment]
Hi, I did a bad push on previous update, this should be fixed now. Can you retry?

Sorry for that

**Comment by kd8azz** [comment]
Same error--

An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: http://bazelbuild.github.io/e4b/p2updatesite/plugins/com.google.devtools.bazel.e4b_0.0.1.201604271311.jar.
http://bazelbuild.github.io/e4b/p2updatesite/plugins/com.google.devtools.bazel.e4b_0.0.1.201604271311.jar
Artifact not found: http://bazelbuild.github.io/e4b/p2updatesite/features/com.google.devtools.bazel.e4b.feature_0.0.1.201604271311.jar.
http://bazelbuild.github.io/e4b/p2updatesite/features/com.google.devtools.bazel.e4b.feature_0.0.1.201604271311.jar

This is version 0.0.1.201604271311.  That doesn't seem right.  Am I doing something wrong, here?

**Comment by damienmg** [comment]
:( Maybe wait a bit?
The previous site had the 0.0.1.XXX version, should be fixed now.

**Comment by damienmg** [comment]
Just installed on my eclipse, no issue...

**Comment by kd8azz** [comment]
I closed and reopened eclipse, and tried again.  It found version 0.0.1 correctly this time.  I'm guessing it was just stuck in my cache.  It installed correctly this time.  Thanks.
