### ISSUE TITLE
Cannot create project

### ISSUE THREAD

**Issue by kd8azz** [bazelbuild/e4b#11]
Hello,

First time user, here.  I'm running 

```
Eclipse IDE for Java Developers
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600
```

on Ubuntu GNOME 16.04.1 LTS 64bit.

I'm hitting [WorkspaceWizardPage.java:166](https://github.com/bazelbuild/e4b/blob/ae17bdebcb1733ff1cb9172043652668fd85725c/com.google.devtools.bazel.e4b/src/com/google/devtools/bazel/e4b/wizard/WorkspaceWizardPage.java#L166) when I try to create a project, at /home/user/Source/Project.  Yet, 

```
 $ ls
/home/user/Source/Project
 $ bazel --watchfs info workspace
/home/user/Source/Project
```

Let me know if there's any other info I can provide.

**Comment by damienmg** [comment]
The message might be misleading: where is bazel? You might want to select the location of bazel in the Eclipse preferences.

**Comment by kd8azz** [comment]
Excellent.

```
$ cd /usr/local/bin/
$ ls bazel
<notice that there is no output>
$ which bazel
/home/user/bin/bazel
$ sudo ln -s /home/user/bin/bazel
$ ls bazel
bazel
```

The plugin gets past that point now.  Thank you.

I see red text in my console, after creating the project, but that might be because I have errors in my workspace.  I'll come back and take a look later.

**Comment by damienmg** [comment]
FTR, https://github.com/bazelbuild/e4b/issues/3 was already opened for the error message.

**Comment by kd8azz** [comment]
Oh, and for posterity that arrives via Google search, the original error message was "does not seems to be a Bazel workspace".  Should have probably included that in the description.
