### ISSUE TITLE
Bazel Classpath Container appears misconfigured

### ISSUE THREAD

**Issue by kd8azz** [bazelbuild/e4b#14]
Hello again,

First, I really appreciate all your help; this'll be my third issue in a row.  My project now is created without error, but the classpath is messed up.  Viewing the classpath in eclipse, I get the following:

```
Bazel Classpath Container
    > hamcrest--all-1.3.jar - /home/user/.cache/bazel/_bazel_user/00bb1210de2173919b75bf7db0a13118/execroot/hamcrestall/jar (missing)
      <about 15 more, equivalent missing jars>
```

The jar in question is actually located at `/home/user/.cache/bazel/_bazel_user/00bb1210de2173919b75bf7db0a13118/execroot/Project/external/hamcrestall/jar`

```
$ ls /home/user/.cache/bazel/_bazel_user/00bb1210de2173919b75bf7db0a13118/execroot/Project/external/hamcrestall/jar
BUILD  hamcrest-all-1.3.jar
```

The relevant portion of my WORKSPACE file:

```
maven_jar(
  name = "hamcrestall",
  artifact = "org.hamcrest:hamcrest-all:1.3",
)
bind(
  name = "org/hamcrest/all",
  actual = "@hamcrestall//jar",
)
```

And a relevant bit of a BUILD file:

```
java_test(
    name = "Thingy3Test",
    srcs = ["Thingy3Test.java"],
    deps = [
        "//external:com/google/guava",
        "//external:com/google/truth",
        "//src/main/path/to",
        "//src/main/path/other",
        "//external:junit/junit",
        "//external:org/hamcrest/all",
        "//external:org/jocl",
    ],
    data = [":smoke_test_data"],
    test_class = "path.to.Thingy3Test",
)
```

**Comment by damienmg** [comment]
Sorry for the delay I haven't had time to look at it yet. (we are in a summit this week)

**Comment by kd8azz** [comment]
Oh, no rush!  I only get to work on my project a day or two per week,
myself.  You are far more responsive than I would expect.

Hope your summit is productive.

**Comment by damienmg** [comment]
Sorry forgot about that issue, I would like to reproduce it, do you have a git repo I can clone to test?

**Comment by damienmg** [comment]
As there was a pretty bad race condition on linux that could have trigger that. I am closing that bug (0.0.4 should fix it).

**Comment by kd8azz** [comment]
Never did verify that this fixed it, but I have switched to IntelliJ, so this is no longer my problem.  Thanks for your help.
