### ISSUE TITLE
Add contributor instructions on how to open project in Eclipse and install a dev version

### ISSUE THREAD

**Issue by nanaze** [bazelbuild/e4b#19]

**Comment by dionescu** [comment]
1. Git clone the repo.
2. Open Eclipse and go to File/Import...
3. Expand Plug-in Development and then select Plug-ins and Fragments from under it. Click Next.
4. In the new window select Import From Directory and use the directory where you cloned e4b. I think the default "Binary projects" should work but try the other options if you see errors.  Click Next.
5. In the new selection Window, select the e4b plugin and click "Add". Click Finish.

You should now see the plugin package in eclipse. Right-click it, then go to Run As, then select Eclipse Application. That should bring up a new instance of Eclipse that has your plugin.

**Comment by damienmg** [comment]
Done at https://github.com/bazelbuild/e4b/wiki/Contributing
