### ISSUE TITLE
did not find "Import Project..." > "Others".

### ISSUE THREAD

**Issue by huijunw** [bazelbuild/e4b#24]
I installed e4b on eclipse, but cannot find the 'import project' 'others'

https://www.dropbox.com/s/xulwene1hnxk3qu/Screenshot%202017-02-08%2014.52.38.png?dl=0

https://www.dropbox.com/s/5d8nqvpp9jq83ln/Screenshot%202017-02-08%2014.53.37.png?dl=0

**Comment by damienmg** [comment]
Oops the correct menu is "New project" then Import Bazel Workspace...
