### ISSUE TITLE
Problems loading bazel itself from eclipse

### ISSUE THREAD

**Issue by r4nt** [bazelbuild/e4b#29]
When importing the current bazel repository, I get an error that the root is not a workspace; apparently it still works, but when adding targets, enter does not add the target, one needs to see the small + at the side.

**Comment by damienmg** [comment]
I confirm that it works for me so might be either ubuntu or the eclipse version. Will do more test when I have time.

**Comment by ngist** [comment]
I think this has to do with the bazel install path on ubuntu. I'm having a similar problem. When I go to import it tells me the same thing.

The path to bazel is set  in [Activator.class](https://github.com/bazelbuild/e4b/blob/de273842050faef69cbaca541923c1c124921346/com.google.devtools.bazel.e4b/src/com/google/devtools/bazel/e4b/Activator.java) to 
`  public static final String DEFAULT_BAZEL_PATH = "/usr/local/bin/bazel";`

In my environment the path is /usr/bin/bazel

I setup a symlink and it took care of the error message but I can't click finish, it stays grey'd out.

**Comment by damienmg** [comment]
I am fixing that at HEAD to show a proper error when Bazel is not found, I haven't cut a new release yet I want to do a bunch of other stuff.

**Comment by damienmg** [comment]
Also another fix at HEAD: there was a race condition in the command invocation on Linux which could largely explain the behaviour @r4nt have seen. I still want to do some more improvements before cutting a release.
