### ISSUE TITLE
Add better error message if bazel binary is not found

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/e4b#3]
Currently the error message "does not seems to be a bazel workspace" shows up during import instead if the bazel binary is not found at the location.

**Comment by bjshively** [comment]
I'm seeing this `does not seems to be a bazel workspace` error when trying to import our source tree. This seems to be erroneous; running bazel from the shell works fine. Is there any guidance on how e4b detects if the folder is a valid bazel workspace?

**Comment by damienmg** [comment]
The plugin use bazel to query the workspace and consider an error to be a problem with the workspace. It looks for bazel in /usr/local/bin/bazel by default and this can be configured in the global settings. This should definitely be improved.
