### ISSUE TITLE
folders sorted incorrectly ubuntu 14.04 and import hangs.

### ISSUE THREAD

**Issue by knightmj** [bazelbuild/e4b#5]
On Ubuntu 14.04 when attempting to select folders to import, the folders are not listed alphabetically.  This does not seem to happen on Darwin. 

Also, I think because of this, the load hangs for a directory with a lot of folders. I think some logic elsewhere may be assuming sorted folders as again this project loads correctly on Darwin. On Ubuntu it locks after pressing Finish on the import.

**Comment by damienmg** [comment]
The code which is doing the listing is really basic and can be found here: https://github.com/bazelbuild/e4b/blob/master/com.google.devtools.bazel.e4b/src/com/google/devtools/bazel/e4b/wizard/DirectoryTreeContentProvider.java

How big is the directory?

**Comment by damienmg** [comment]
I fixed a race condition on linux that might addressed that. Closing without any way to repro.
