### ISSUE TITLE
Eclipse for bazel, how to run project?

### ISSUE THREAD

**Issue by Abwahabbab** [bazelbuild/e4b#53]
Creating a bazel project according to https://bazel.build/versions/master/docs/tutorial/cpp.html works

Running "bazel build main:hello-world" in ~/project works with the output "hello world + time" in console

Importing the project into eclipse using "import bazel workspace" works

However, in elcipse menu, "Project/Build project" is greyed out.

Pressing the green run button does not run the application

Right clicking on the project and selecting "Run as" only gives the "run configuration" option with a greyed out run button

How to run and debug this application like normally when using eclipse CDT?

**Comment by damienmg** [comment]
Hello there is no support for CDT, see #21 for the corresponding feature request.
