### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hblok** [bazelbuild/e4b#57]
Could we please have a new release? There are a couple of improvements which have gone in since the 0.0.2 release a year ago. It would be great to enjoy them.

**Comment by damienmg** [comment]
I have done a new release pipeline, now releasing :)

**Comment by damienmg** [comment]
New release done: https://storage.googleapis.com/eclipse.bazel.build/updatesite/

When the DNS cl get approve it should be available at https://eclipse.bazel.build/updatesite

**Comment by hridder** [comment]
Works now. Thanks!

For others: note the change in the update site URL, which is different than before.
