### ISSUE TITLE
AutoValue annotation processor support

### ISSUE THREAD

**Issue by psaville-google** [bazelbuild/e4b#7]
I've added in my base BUILD a java_plugin definition to support compiling java rules with @AutoValue support.
[AutoValue github](https://github.com/google/auto/tree/master/value)

I found this example that makes `bazel build` work:
[Bazel AutoValue `java_plugin` example](https://gist.github.com/cushon/0ffbe4f2a11141106695)

I'm still using a setup-eclipse script that manages the project classpath for building etc. And everything has been working great as I add new external dependencies. I've been manually editing the e4b settings file as I need (only editing target? entries).

The problem is now, eclipse cannot understand the AutoValue generated class name, even though the bazel build successfully creates it. I suppose I could custom add a bazel-genfiles dependency manually?

Any ideas how to move forward with this?
Thanks.

**Comment by damienmg** [comment]
Humm that's kind of weird. Bazel does have usage of AutoValue and it works fine.

Is the AutoValue's library in the transitive dependencies of the target in the e4b settings file? Have you try creating a new project from scratch in eclipse?

**Comment by damienmg** [comment]
I consider this bug a side effect of the race condition I fixed recently, closing for now.
